###########################################################################
#                                                                         #
#   Webserver configuration section                                       #
#                                                                         #
#   Find here the default port configuration of the backend server        #
#   and the ssl configuration.                                            #
#                                                                         #
###########################################################################
server:
  port: 9090

websocket:
  endpoint: /ws
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: src/main/resources/opencelium.p12
#    key-store-password: root
#    key-password: root
#    key-alias: tomcat

###########################################################################
#                                                                         #
#   Database configuration section of MariaDB and MongoDB                 #
#                                                                         #
###########################################################################
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/opencelium?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    username: opencelium
    password: secret1234
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://oc_admin:secretsecret@mongodb:27017/opencelium
  #     Example - mongodb://<username>:<password>@<host>:<port>/<database>
  ###########################################################################
  #                                                                         #
  #   Mail configuration section                                            #
  #                                                                         #
  ###########################################################################
  #  mail:
  #    opencelium:
  #      from: noreply@opencelium.io
  #  #    enabled: false
  #    host: smtp.gmail.com
  #    port: 587
  #    username:
  #    password:
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          connectiontimeout: 5000
  #          timeout: 5000
  #          writetimeout: 5000
  #          starttls:
  #            enable: true
  #        ssl:
  #          trust: example.host.de
  ###########################################################################
  #                                                                         #
  #   Configuration of third part tools                                     #
  #                                                                         #
  ###########################################################################
  #  ldap:
  #    embedded:
  #      base-dn: dc=springframework,dc=org
  #      ldif: classpath:test-server.ldif
  #      port: 8389
  #      url: ldap://localhost:8389/
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  ###########################################################################
  #                                                                         #
  #   Basic configuration section. Do not change the following              #
  #   configuration.                                                        #
  #                                                                         #
  ###########################################################################
  main:
    banner-mode: "off"
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      dll-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000000KB
      max-request-size: 1000000KB
  http:
    multipart:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            tablePrefix: QRTZ_
    job-store-type: jdbc
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  mvc:
    throw-exception-if-no-handler-found: true #enables exception handling for endpoints that is not defined in controllers
  web:
    resources:
      add-mappings=false:
  ######################################################################
  #                                                                    #
  #   LDAP configuration section.                                      #
  #   LDAP DEBUG mode can be enabled with the                          #
  #   logging.level.org.springframework.data.ldap: DEBUG settings      #
  #                                                                    #
  ######################################################################
  security:
#    ldap:
#      # LDAP server URL
#      urls: ldap://localhost:7389
#      # User search base
#      user-search-base: ou=User,ou=group,dc=domain,dc=com
#      # Group search base
#      group-search-base: ou=Groups,ou=group,dc=domain,dc=com
#      # LDAP manager credentials
#      username: uid=super_user,ou=User,ou=group,dc=domain,dc=com
#      password: PASSWORD
#      # Where to search for roles/groups
#      # Usually, the unique identifier for OpenLDAP is uniqueMember={0},
#      # while for Active Directory, it is member={0} but check your LDAP settings
#      group-search-filter: (member={0})
#      # User search filter
#      # Usually, the unique identifier for OpenLDAP is mailPrimaryAddress={0},
#      # while for Active Directory, it is mail={0} but check your LDAP settings
#      user-search-filter: (mailPrimaryAddress={0})
#      # Maps groups between LDAP and the application
#      group-role-mapping:
#        - ldap-group: cn=AdminLdap, ou=Groups,ou=group,dc=domain,dc=com
#          oc-role: Admin
#        - ldap-group: cn=UserLdap,ou=Groups,ou=group,dc=domain,dc=com
#          oc-role: User
#      # Default role if no mapping is found between LDAP and the application
#      default-role: User
#      # Timeout for LDAP authentication (in milliseconds)
#      timeout: 30000

springdoc:
  swagger-ui:
    path: /docs
    supportedSubmitMethods:
      - get
      - put
      - post
      - delete
      - options
      - head
      - patch
      - trace
    tagsSorter: alpha
    open-api-custom-settings:
      extensions:
        x-links-enabled: false
  default-produces-media-type: application/json

logging:
  file: src/main/resources/logs
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        data:
          # Activate or deactivate logs during LDAP authentication
          ldap: OFF # OFF or DEBUG;

management:
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          OUT_OF_SERVICE: 200
          DOWN: 200
          UP: 200

opencelium:
  version: 4.7
  ###########################################################################
  #                                                                         #
  #   Is customizable                                                       #
  #                                                                         #
  ###########################################################################
  debug-mode: true
  connector:
    security:
      key: keykeygjhgjh # used for encrypt and decrypt request data
    master-password: # put your master password
  token:
    secret: 84bbce3d33de467b47b7e76c2563769!3f9aff968def8ef2674856f67ae8a93f
    activity-time: 18000
    experation-time: 86400
  ###########################################################################
  #                                                                         #
  #   Configuration for Notification                                        #
  #                                                                         #
  #   for handling several webhooks separate url "," and then webhook       #
  #   notification:                                                         #
  #    tools:                                                               #
  #      income-webhook:                                                    #
  #        url: webhook                                                     #
  #                                                                         #
  ###########################################################################
  notification:
    tools:
      incoming-webhook:
        url: # insert your webhook url here
  installation:
    type: docker
  service-portal:
    base-url: https://service.opencelium.io
    token: your-token-here
  ###########################################################################
  #                                                                         #
  #   Polyglot Engine Configuration                                         #
  #   You can enable Python 3, Ruby, or GraalVM JS                          #
  #   using this configuration.                                             #
  #                                                                         #
  #   By default OC uses Nashorn JS                                         #
  #                                                                         #
  ###########################################################################
#  polyglot:
#    # Enables or disables the polyglot service integration.
#    # Default: false
#    enabled: false
#
#    # Communication protocol used to connect to the polyglot service.
#    # Supported: grpc (default), http (future)
#    # Default: grpc
#    protocol: grpc
#
#    # Host address of the polyglot service.
#    # Default: 127.0.0.1
#    host: '127.0.0.1'
#
#    # Port number of the polyglot service.
#    # Default: 6566
#    port: 6566
#
#    # Automatically starts the polyglot service JAR if not running.
#    # If false, assumes the service is already running externally.
#    # Default: false
#    auto-start: false
#
#    launch:
#      # Path to the polyglot service JAR file.
#      # Required only if auto-start is true.
#      # Example: /opt/polyglot/polyglot-service.jar
#      jarPath:
#
#      # Command-line arguments passed to the polyglot service.
#      args:
#
#      # Maximum time (in seconds) to wait for the service to start and respond.
#      # Default: 30
#      waitTimeoutSec: 30
#
#      # JVM arguments used when launching the polyglot service.
#      # Adjust for performance or memory tuning.
#      # Default: "-Xms64m -Xmx256m"
#      jvmArgs: '-Xms64m -Xmx256m'
#
#      # Enables forwarding of logs produced by the external polyglot JAR
#      # to this applicationâ€™s logging system.
#      # Default: false
#      external-log-enabled: false

#  support:
#    file:
#      directory: src/main/resources/support-files
#      limit:
#        success: 1
#        fail: 5
#  log:
#    retention:
#      per-connection:
#        success: 2
#        fail: 3
#  rest-template:
#    proxy:
#      host: 127.0.0.1
#      port: 8082
#      username: ####
#      password: ####
#  online-services:
#    invoker-sync:
#      time: 0 0 0 * * *
#      active: "false"
#    template-sync:
#      time: 0 0 0 * * *
#      active: "false"
#    active: "false"